name: 'Token retriever'
description: 'Retrieves a token'
author: 'CompliancePal'

inputs:
  token:
    required: true
    description: token

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  color: 'orange'
  icon: 'pocket'
